### ISSUE TITLE
Revert semantics?

### ISSUE THREAD

**Issue by joshma** [ForbesLindesay/redux-optimist#15]
Is there any documentation on how the revert is performed? In the README example, if I ADD_TODO 3 times, and the first one reverts, will the 2nd and 3rd ADD_TODOs go through? Does it just re-apply them to the original state?

**Comment by martypenner** [comment]
Hi Josh, yes, the 2nd and 3rd `ADD_TODO` actions will go through. The revert process looks like this:
1. Restore the entire state to what it was just before the action that's being reverted was fired;
1. Replay all subsequent actions until there are no more left.

Does that help?

**Comment by joshma** [comment]
@martypenner does that assume that actions are independent then? In this case, "append" is independent so you can attempt to do `f(f(f(intitialState, A), B), C)`, rollback the A, and then `f(f(initialState, B), C)` is still correct.

If the function `f` is not independent, say "delete at index", then if you "delete at 0" and follow that with "delete at 1" (so you're really deleting the 1st and 3rd items in the original list), if you roll back "delete at 0" you end up only doing "delete at 1", which deletes the 2nd item.

I'm thinking it'd be nicer to retry the initial action and refuse to allow a revert, since at that point there's no way to cleanly revert. I'm just doing some casual research on what folks are doing for optimistic updates, so at this point I'm just curious what your thoughts are!

**Comment by Macil** [comment]
What do you mean by retrying the initial action? Taking the action out of history and putting it back in won't change anything unless you have non-deterministic reducers.

redux-optimist doesn't know if some actions are dependent on others, so it couldn't know which actions to not allow to be reverted.

**Comment by joshma** [comment]
Hm, so I can try to clarify: given actions `DELETE(0)` and `DELETE(1)`, redux-optimist can apply two strategies if DELETE(0) fails:
1) User says "revert DELETE(0)", redux-optimist says "OK, then I'll apply only DELETE(1)" - this leads to the issues I mentioned above.
2) User sees "DELETE(0) failed" and retries. redux-optimist doesn't do anything other than keep the initial state around. If DELETE(0) absolutely cannot succeed, user says "revert DELETE(0)" and redux-optimist reverts back to the initial state - it **does not** apply DELETE(1).

You're right that, in the 2nd case, since reducers should be deterministic as long as you don't remove an action from the history the optimistic state shouldn't change. However, in the 1st case, which is what I think redux-optimist is doing right now, the optimistic history would change and the user's state would drift from the server's.

**Comment by ForbesLindesay** [comment]
I would strongly advise against actions that are DELETE_AT_INDEX.  Instead, use DELETE_BY_ID.  Since you may (probably will) want to have some middleware that is asynchronous (i.e. makes requests to the server) you don't want to create dependencies between separate actions.  What if you fire `deleteAt(0)` and `deleteAt(1)` and both of these are held up by async middleware for a brief moment.  You meant to delete the first two items in the list, but what actually happens is you delete the first item in the list, then delete the new second item in the list. i.e. `[1, 2, 3]` becomes `[2]` instead of `[3]`.

Reverting to the initial state (i.e. discarding all subsequent actions as you suggest in 2) is much simpler to implement, but not very useful.  It is normal to keep all your state in redux, so many of the actions may be completely un-related.  Reverting all subsequent actions will typically leave your app in a very broken state.

Retries are best handled outside of redux-optimist.  You can put them in your middleware:

``` js
// N.B. this code has not been tested

import {BEGIN, COMMIT, REVERT} from 'redux-optimist';
import request from 'then-request';

function retry(fn) {
  return new Promise((resolve, reject) => {
    function attempt(n) {
      fn().done(resolve, err => {
        if (n < 4) setTimeout(() => attempt(n + 1), n * n * 100);
        else  reject(err);
      });
    }
    attempt(0);
  });
}

let nextTransactionID = 0;
export default function (store) {
  return next => action => {
    if (action.type !== 'ADD_TODO') {
      return next(action);
    }
    let transactionID = nextTransactionID++;
    next({
      type: 'ADD_TODO',
      text: action.text,
      optimist: {type: BEGIN, id: transactionID}
    });
    retry(() => request('POST', '/add_todo', {text: action.text}).getBody()).done(
      res => next({
        type: 'ADD_TODO_COMPLETE',
        text: action.text,
        response: res,
        optimist: {type: COMMIT, id: transactionID}
      }),
      err => next({
        type: 'ADD_TODO_FAILED',
        text: action.text,
        error: err,
        optimist: {type: REVERT, id: transactionID}
      })
    );
  }
};
```
