### ISSUE TITLE
Action implementation

### ISSUE THREAD

**Issue by joecritch** [ForbesLindesay/redux-optimist#6]
I have two questions about implementing optimistic actions:

(1) For the asynchronous ADD_TODO action, is it only ADD_TODO that needs to be initially called by my own action creator? And the middleware handles the corresponding _COMPLETED and _FAILED dispatches?

(2) How would the `api.js` middleware handle multiple action types? (E.g. DELETE_TODO?) Would I need a separate middleware for every action type?

Thanks in advance.

**Comment by ForbesLindesay** [comment]
1. Yes, the action creators should create actions for api calls, then the middleware creates actions for success/failure
2. The middleware is something you write yourself, so it's up to you.  You could have a generic `API_CALL` action type, and handle that in middleware.  You could add a property to your api call actions and look for that, rather than a type, in your middleware.

**Comment by joecritch** [comment]
Thanks, this is working well so far. I'll try and get an example put together for future reference.

**Comment by ForbesLindesay** [comment]
Thanks, I'll close this issue, but feel free to keep commenting or open a new issue if you have more questions/suggestions.
